using System.IO;
using Hast.Common.Interfaces;
using Hast.Synthesis.Models;

namespace Hast.Synthesis.Services
{
    /// <summary>
    /// Services for reading and parsing the timing report generated by Hastlayer Timing Tester. These timing reports
    /// contain hardware timing information on binary operations.
    /// </summary>
    public interface ITimingReportParser : ISingletonDependency
    {
        ITimingReport Parse(TextReader reportReader);
    }

    public static class TimingReportReaderExtensions
    {
        public static ITimingReport Parse(this ITimingReportParser reportParser, string reportContent)
        {
            using var stringReader = new StringReader(reportContent);
            return reportParser.Parse(stringReader);
        }
    }
}
