name: Validate Pull Request

on:
  pull_request:

jobs:
  validate-workflow:
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-submodule-pull-request.yml@dev
    with:
      repository: "Lombiq/Hastlayer-SDK"
